[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
freelancepay = "5Xw3NMeBryNtdb2Hpg6pU1HqkpT9ymx6aScstd1T8NTX"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
